virt: lxd
language: android

before_script:
  - 'export PATH="$HOME/.local/bin:$PATH"'
  - pyenv install --list
  - pyenv install --skip-existing 3.6.2 && pyenv global 3.6.2
  - python3 -m pip install --upgrade pip
  - python3 -m pip install --user google-api-python-client oauth2client httplib2 pyOpenSSL

script:
  - ./gradlew test
  - releases/travis_build.sh

after_script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && releases/publish_s3.sh'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && python3 releases/publish_playstore_v3.py'

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

sudo: true
before_install:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_6a3fa2e8cfe5_key -iv $encrypted_6a3fa2e8cfe5_iv
    -in releases/google-play-key.p12.enc -out releases/google-play-key.p12 -d || true'
  - sed -i "s/versionCode.*/versionCode = $(git rev-list HEAD --first-parent --count)/" app/build.gradle.kts
  # https://stackoverflow.com/a/47726910/1449683
  - yes | sdkmanager "platforms;android-27"

# Workaround for https://github.com/travis-ci/travis-ci/issues/4942
git:
  depth: 99999

notifications:
  irc:
    channels:
      # travis encrypt "ircs://irc.libera.chat:6697/#weechat-android" -r ubergeek42/weechat-android
      - secure: "n9SW5kjNz2vNg/CYhy25qO2FuwhMDRlUyjkcIqhatAi43pyqMu0Pjj9LNPxvQhD4A3oWYOFWqHix/Ydq6223fKHG9JtP3QIF/tyhuOSShm9pAQxz5jKze+TM+sRiC+SGyNaJpymF6gPWqQCvRaQHg9GlxXoRKgmANM2dCyxkAEU="
    template:
      - "#%{build_number} (%{commit} @ %{branch} by %{author}): %{message}"
      - "Message: %{commit_subject}"
      - "Changes: %{compare_url}"

# Edit this line when you want to trigger a travis build. Count: 6
